from typing import Protocol, Optional, List, Dict, Any
from domain.models import Recording, Evidence, DiscoveryCandidate, DiscoveryScore
from domain.sonic import SonicFeature, AudioVector, SonicSimilarityResult

class IRecordingRepo(Protocol):
    def get_by_id(self, recording_id: str) -> Optional[Recording]: ...
    def save(self, recording: Recording) -> None: ...
    def get_overview_catalog(self, filters: Optional[Dict[str, Any]] = None) -> List[Recording]: ...

class IArtistRepo(Protocol):
    def get_or_create(self, name: str, country: Optional[str] = None, region: Optional[str] = None, mbid: Optional[str] = None) -> str: ...
    def update_demographics(self, artist_id: str, **kwargs: Any) -> None: ...

class IAlbumRepo(Protocol):
    def get_or_create(self, title: str, artist_id: str, **kwargs: Any) -> str: ...

class IEvidenceRepo(Protocol):
    def add_batch(self, evidence_list: List[Evidence]) -> None: ...
    def get_for_entity(self, entity_id: str, field_name: Optional[str] = None) -> List[Evidence]: ...

class IDiscoveryRepo(Protocol):
    def save_candidates(self, candidates: List[DiscoveryCandidate], scores: List[DiscoveryScore]) -> None: ...

class ISonicRepo(Protocol):
    def save_features(self, features: SonicFeature) -> None: ...

class IUnitOfWork(Protocol):
    recordings: IRecordingRepo
    artists: IArtistRepo
    albums: IAlbumRepo
    evidence: IEvidenceRepo
    discovery: IDiscoveryRepo
    sonic: ISonicRepo

    def __enter__(self) -> "IUnitOfWork": ...
    def __exit__(self, exc_type: Any, exc_val: Any, exc_tb: Any) -> None: ...